# Generated by Django 5.1.5 on 2025-03-23 06:58

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=Api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
